version: '3'

services:
  mongo1:
    image: "mongo-start"
    build: ./.docker/mongodb/setup-start
    env_file: "./src/pre-start/env/${ENV-development}.env"
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"
    depends_on:
      - "mongo2"
      - "mongo3"
    container_name: mongo1

  mongo2:
    image: "mongo:${DB_VERSION:-5.0.0}"
    command: --replSet rs0
    ports:
      - "27018:${DB_PORT:-27017}"
    container_name: mongo2
    env_file: "./src/pre-start/env/${ENV-development}.env"

  mongo3:
    image: "mongo:${DB_VERSION:-5.0.0}"
    command: --replSet rs0
    ports:
      - "27019:${DB_PORT:-27017}"
    container_name: mongo3
    env_file: "./src/pre-start/env/${ENV-development}.env"

  setup-replica-set:
    image: "setup-replica-set"
    build: ./.docker/mongodb/setup-replica-set
    restart: "no"
    depends_on:
      - "mongo1"