@startuml
skinparam linetype ortho
!theme plain

package Game <<Rectangle>> {

  entity Level {
    + id: number (PK)
    --
    * name: string
    * layer: number
    --
    # categories: Document<Category>[]
  }

  entity Category {
    + id: number (PK)
    --
    * iconUrl: string
    * name: string
    * description: string
    --
    # tasks: Document<Task>[] (FK)
  }

  entity Task {
    + id: number (PK)
    --
    * name: string
    * description: string
    * question_count: number
    --
    * nodes: Subdocument<Node>[]
  }

  entity Node {
    * title: string
  }

  entity ImageNode extends Node {
    * imageUrl: string
    * imageAlt: string
  }

  entity TextNode extends Node {
    * text: string
  }

  entity AnswerNode extends Node {
    * question: string
  }

  entity Box {
    + id: number (PK)
    --
    * try: number
    --
    # category: Document<Category> (FK)
    * tasks: Subdocument<BoxTask>[]
  }

  entity BoxTask {
    # task: Document<Task> (FK)
    * task.answer
  }

  Level ||--o{ Category
  Category ||---o{ Task
  Box }o-r-|| Category
  Box ||---|{ BoxTask
  BoxTask ||---|| Task
  Task ||-d-|{ Node
}

note top of Game
    <i>Considering a NoSQL db engine</i>
end note

package User <<Rectangle>> {

  entity User {
    + id: number (PK)
    --
    * email: string
    * name: string
    * sex: number
    * birthday: string
    * password: string
    * tries: number
    --
    # level: Document<Level> (FK)
    # category: Document<Category> (FK)
    # box: Document<Box> (FK)
    # history: Document<Box>[] (FK)
  }

  User }o-o| Level
  User }o-o| Category
  User ||-o| Box
  User ||-o{ Box

}

@enduml
