@startuml
skinparam linetype ortho
!theme plain

package Game <<Rectangle>> {

  entity Level {
    + id: number (PK)
    --
    * name: string
    * layer: number
    --
    categories: Document[]
    # categories.id: number (FK)
  }

  entity Category {
    + id: number (PK)
    --
    * iconUrl: string
    * name: string
    * description: string
    --
    tasks: Document[]
    # tasks.id: number (FK)
  }

  entity Task {
    + id: number (PK)
    --
    * name: string
    * description: string
    --
    * nodes: object[]
    * nodes.title: string
    * nodes.type: string
    * nodes.data: object
  }

  entity Box {
    + id: number (PK)
    --
    * try: number
    --
    tasks: Document[]
    # tasks.id: number (FK)
    task.right: boolean
  }

  Level ||-d-o{ Category
  Category ||-d-o{ Task
  Box }o-r-|| Category
  Box ||-d-o{ Task
}

note top of Game
    <i>Considering a NoSQL db engine</i>
end note

package User <<Rectangle>> {

  entity User {
    + id: number (PK)
    --
    * email: string
    * name: string
    * sex: number
    * birthday: string
    * password: string
    * tries: number
    --
    level: Document
    # level.id: number (FK)
    category: Document
    # category.id: number (FK)
    box: Document
    # box.id: number (FK)
    history: Document[]
    # history.id (FK)
  }

  User }o-o| Level
  User }o-o| Category
  User ||-o| Box
  User ||-o{ Box

}

@enduml
