name: Build Server
on:
  push:
    branches:
      - main
      - revision
      - ci

  pull_request:
    branches:
      - main
      - revision
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installation
      run: npm ci

    - name: Tests
      run: npm test

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./server/coverage/clover.xml
        verbose: true
        fail_ci_if_error: true